default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: widgets_development

test:
  <<: *default
  database: widgets_test

production:
  <<: *default
  database: widgets_production
  username: widgets
  password: <%= ENV['WIDGETS_DATABASE_PASSWORD'] %>
